[project]
name = "todo-app"
version = "0.1.0"
description = "Simple FastAPI Todo List"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
]

[tool.uv]
dev-dependencies = []

[project.scripts]
start = "uvicorn main:app --host 0.0.0.0 --port 8000" 